### ISSUE TITLE
When can the code be uploaded

### ISSUE THREAD

**Issue by ZhaoLiruii** [DiT-3D/FastDiT-3D#1]
When can the code be uploaded? Really need @DiT-3D

**Comment by DiT-3D** [comment]
Thanks for your interest! Our paper is still under review.

**Comment by ZhaoLiruii** [comment]
Could you please send the code of the foreground-background voxel mask to my email? I would like to refer to the code of this part, because there was a problem when I reproduced it


1213230008
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DiT-3D/FastDiT-3D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月23日(星期六) 上午8:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DiT-3D/FastDiT-3D] When can the code be uploaded (Issue #1)





 
Closed #1 as completed.
