### ISSUE TITLE
May I ask if I have obtained the code

### ISSUE THREAD

**Issue by DongshuoH** [DiT-3D/FastDiT-3D#2]
Thank you for your work. I am working on an enhanced framework for point cloud generation. Part of our products are plug and play and can be easily replaced. May I obtain the code for Fast Det3d as part of my experiment. I will strongly emphasize that Dit-3D was used in this section. If i can.My email is hds13075386577@163.com.
It's okay if not, thank you for the great work you've done.

**Comment by DiT-3D** [comment]
Hi, thanks for your interest. We will release the code soon.
